### ISSUE TITLE
vmware sample does not work without disableComponents and 'cloudController'

### ISSUE THREAD

**Issue by donovanmuller** [rancher/cluster-api-provider-rke2#227]
**What happened:**

When using https://github.com/rancher-sandbox/cluster-api-provider-rke2/tree/main/samples/vmware, the first control plane Node would never pass the preflight checks due to the Node `ProviderID` not matching the vsphere ProviderID (see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2400).

This is because the RKE cloud controller starts before the vsphere CPI is installed and sets the ProviderID to the RKE value, which won't be overwritten by the vsphere CPI once it's running.

Adding the following to https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/samples/vmware/rke2controlplane.yaml disabled the RKE cloud controller and allowed the vsphere CPI to set the ProviderID properly:

```yaml
  serverConfig:
    disableComponents:
      kubernetesComponents:
        - cloudController
```

**What did you expect to happen:**

The first control plane Node to pass the preflight checks.

**How to reproduce it:**

Use the vpshere example as-is.

**Anything else you would like to add:**

If this is not expected, the sample should be updated to disable the `cloudController`.

**Environment:**

- rke provider version: `v0.2.2`
- RKE2 version: `v1.26.11+rke2r1`

**Comment by donovanmuller** [comment]
See https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/268#issuecomment-1956346059

**Comment by furkatgofurov7** [comment]
@donovanmuller Hey, the new provider version (v0.2.5) has been released, can you verify if it solves this issue?
