### ISSUE TITLE
Create CAPI node image with RKE2 CLI

### ISSUE THREAD

**Issue by belgaied2** [rancher/cluster-api-provider-rke2#24]
**Describe the solution you'd like:**
CAPI Bootstrap provider needs a node image containing the basic tools for bootstrapping the cluster.
- [ ] Define the approach to install RKE2 that would satisfy the Air-Gapped mode and the connected mode
- [ ] Define the pre-requisites to the installation
- [ ] Decide which OS should be used for base images
- [ ] Automate creation of the node image for multiple backends (AWS, OpenStack/KVM, VMWare, etc.)

**Why do you want this feature:**
Necessary to the bootstrap provider.

**Comment by kkaempf** [comment]
Hmm, we could use SLE Micro for Rancher as a base image 🤔 /cc @agracey

**Comment by alexander-demicev** [comment]
We might want to take a look into https://github.com/kubernetes-sigs/image-builder for building the image since it already supports the most popular cloud providers.

**Comment by belgaied2** [comment]
A couple of constraints about the choice of the OS:
- It should support `cloud-init` which [is not the case for OpenSUSE Leap Micro](https://get.opensuse.org/leapmicro/5.2/#download) but is the case for [SLE Micro for Rancher](https://rancher.github.io/elemental/quickstart#what-is-the-rancher-elemental-stack-) or [OpenSUSE Leap Cloud](https://get.opensuse.org/leap/15.4/#download).
- It should support SELinux as this might be an important part of RKE2's security settings.
- It should be compatible with edge scenarios (might be implemented with Bare Metal or, in the future, small footprint devices with K3s), this means `SLE Micro for Rancher` is probably better than `OpenSUSE Leap` ?
- The image should work correctly in Air-Gapped environments.
- The image will include the RKE2 binaries baked-in.

**Comment by belgaied2** [comment]
> We'd have to have our own version of image-builder as we wouldn't be able to include RKE2 into that project directly. But we can still use it as a basis or use our own image building mechanism.

I think the answer to the image building mechanism might dependent on the exact OS to use. For example, if we use `SLE Micro for Rancher`, we might benefit from discussing that with the Elemental team.

**Comment by belgaied2** [comment]
Looks like `SLE Micro for Rancher` is not a good choice when there is no Rancher available.
It looks like we would have 2 possible choices:
- OpenSUSE Leap
- Ubuntu (used by other CAPI projects)

**Comment by agracey** [comment]
SLE Micro for Rancher is a fine choice. Elemental Teal is not.

**Comment by belgaied2** [comment]
IMHO, we should stick to whatever CAPI does for now, meaning:
- We use Ubuntu
- We use a variation of [image builder](https://github.com/kubernetes-sigs/image-builder )

@agracey SLE Micro for Rancher could always be supported in the future. Images could even be built in a different way. CAPBR should work just fine as long as cloud init is supported and RKE2 binaries are available in the same locations.

**Comment by richardcase** [comment]
I think that's a good position to start at @belgaied2 👍

**Comment by belgaied2** [comment]
As of 

> Define the approach to install RKE2 that would satisfy the Air-Gapped mode and the connected mode

After a discussion with @richardcase , it looks like the best way to begin would be to suppose that all pre-requisites for installing RKE2 are on the OS image. This solution is used by CAPI upstream (e.g. for CABPK) and works great for both Air-Gapped and connected modes.

Any arguments against this approach ? Let's discuss.

**Comment by kkaempf** [comment]
> [...] that all pre-requisites for installing RKE2 are on the OS image. 

What would that include ?

**Comment by belgaied2** [comment]
@kkaempf Actually not much:
- SELinux
- about 5-6 tar files and the rke2 binary from RKE2's release assets (specific to each RKE2 version)
- install shell script from https://get.rke2.io 

There are might be some other details about how the OS should be configured, but these can be figured out during testing.

**Comment by kkaempf** [comment]
Ok, piece of cake 😆 

We could start building such an image [within Elemental Teal](https://build.opensuse.org/project/show/isv:Rancher:Elemental:Dev:Teal53) or create a separate [isv:Rancher:...](https://build.opensuse.org/project/show/isv:Rancher) subproject for this.

**Comment by alexander-demicev** [comment]
Closing the issue, this will be addressed separately
