### ISSUE TITLE
Add dual-stack support

### ISSUE THREAD

**Issue by amold1** [rancher/cluster-api-provider-rke2#337]
**Describe the solution you'd like:**
I would like to get cluster-api-provider-rke2 to provide dual-stack support. 

**Why do you want this feature:**
From the docs in the [old](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/docs/old/RKE2%20Cluster%20API%20Provider%20-%20Data%20Type%20definitions.md?plain=1#L170-L176) section, you could pass the cluster and service cidr to the config but looks like that is not supported anymore. [The code](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/docs/old/RKE2%20Cluster%20API%20Provider%20-%20Data%20Type%20definitions.md?plain=1#L170-L176)
 says this is not exposed so I am wondering how I can get dual-stack setup to work. 
I am following [this guide](https://docs.rke2.io/networking/basic_network_options#dual-stack-configuration) to get dual-stack to work with cilium.

**Anything else you would like to add:**
My`RKE2ControlPlane` spec to add cidr
```
  serverConfig:
    clusterCidr: 10.192.0.0/10,fd02::/80
    serviceCidr: 10.96.0.0/12,fd03::/108
```
error on applying
```
Error from server (BadRequest): error when creating "STDIN": RKE2ControlPlane in version "v1alpha1" cannot be handled as a RKE2ControlPlane: strict decoding error: unknown field "spec.serverConfig.clusterCidr", unknown field "spec.serverConfig.serviceCidr"
```

If this is indeed already supported, I'd appreciate some guidance/documentation to help me out.

Thanks.

**Comment by greenmaid** [comment]
I would have the same expectation here. I'm trying to have a dual stack cluster using calico CNI.

It seems that currently capbr does not support multiple pod/service cidrs blocks and only takes only the first one configured

https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/07eef9b691dcec2d7b9458ef577e8758507a7396/pkg/rke2/config.go#L190-L199

**Comment by alexander-demicev** [comment]
Closing it for now, we don't have the capacity to work on it.
