### ISSUE TITLE
CAPRKE2 patch release 

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/cluster-api-provider-rke2#458]
Create a new patch release that includes recent ETCD fixes

**Comment by Danil-Grigorev** [comment]
Released 2 new patch versions:
- https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.7.1
- https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.2.8

**Comment by ron1** [comment]
Issue should be closed.

**Comment by furkatgofurov7** [comment]
https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.7.1 was released to address this, closing it.
