### ISSUE TITLE
RKE2 extraMounts can't be used: are arrays in RKE2 native config, but maps in CRDs

### ISSUE THREAD

**Issue by tmmorin** [rancher/cluster-api-provider-rke2#476]
We were made aware of the following issue via Sylva project users.

The CRDs CAPI RKE2 bootstrap/controlplane provider have `extraMounts` specified as a `map` (in many place), which is directly mapped to RKE2 config, which does not work because RKE2 config for these fields needs an `array`.

Example with `KubeAPIserver`

https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/4ee00727b19600245edddec9d5ae8a1e6c48a862/bootstrap/api/v1beta1/rke2config_types.go#L396
```
	ExtraMounts map[string]string `json:"extraMounts,omitempty"`
```
controller:

https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/fa98e1f9c747b43f803de99999f5c85e9ebe50f6/pkg/rke2/config.go#L344
```
		rke2ServerConfig.KubeAPIserverExtraMounts = opts.ServerConfig.KubeAPIServer.ExtraMounts
```

RKE2 native config:
https://github.com/rancher/rke2/blob/e1ba484a0916d885b1f211a9e284e3a5570b8d45/pkg/rke2/rke2.go#L48C1-L49C40
```
type ExtraMounts struct {
	KubeAPIServer          cli.StringSlice
```

**Comment by hardys** [comment]
I raised a related issue as I think this is still not working correctly - details in https://github.com/rancher/cluster-api-provider-rke2/issues/524
